import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ColumnSelectionProvider } from "@/context/queryContext";
import ThemeToggleButton from "./components/ToggleButtonTheme";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen w-screen dark:bg-gray-800 dark:text-gray-100`}
      >
        <ColumnSelectionProvider>
        <div className="w-full h-[10vh] flex justify-between px-8 py-2">
          <h1 className="text-2xl font-bold mb-4">Query Builder</h1>
          <ThemeToggleButton />
        </div>
        <div className="  h-[90vh]  ">
          {children}
        </div>
      
        </ColumnSelectionProvider>

      </body>
    </html>

  );
}
